#!/bin/bash
#
# temp build script
#

TARGET="$1"
BUILD="$2"

build_config () {
	rm -rf corefs-builder/configs/*
	rm -rf corefs-builder/board/*
	rm -rf output/*
	rm -rf corefs-builder/system/skeleton/*
	cat boards/"$TARGET"/board.conf > corefs-builder/configs/active_defconfig
	cat boards/"$TARGET"/config/linux.conf >> corefs-builder/configs/active_defconfig
	cat boards/"$TARGET"/config/uboot.conf >> corefs-builder/configs/active_defconfig
	cat config/buildroot/buildroot.conf >> corefs-builder/configs/active_defconfig
	cat config/iotfapOS-core.conf >> corefs-builder/configs/active_defconfig
	cat config/iotfapOS-custom.conf >> corefs-builder/configs/active_defconfig
	cp -r boards/"$TARGET"/* corefs-builder/board/
	cp -r config/* corefs-builder/configs/
	cp -r config/skel/* corefs-builder/system/skeleton/
	cp -r boards/"$TARGET"/skel/* corefs-builder/system/skeleton/
	COREFS_SIZE=`cat corefs-builder/board/board.conf | grep TB_COREFS_SIZE | cut -d "=" -f 2 | sed "s/\"//g"`
	if [ ! -z "$COREFS_SIZE" ]; then
		sed -i "s/32M/$COREFS_SIZE/g" corefs-builder/configs/active_defconfig
	fi
}

build () {
	case "$BUILD" in 
		all)
			make_all
			;;
		linux)
			make_linux
			;;
		corefs)
			make_corefs
			;;
		uboot)
			make_uboot
			;;
		clean)
			make_clean
			;;
		*)
			make_edit
			;;
esac
}

make_all () {
	cd corefs-builder
	make active_defconfig
	make -s
	cp output/images/* ../output/
}

make_corefs () {
	sed -i 's/BR2_LINUX_KERNEL=y/BR2_LINUX_KERNEL=n/g' corefs-builder/configs/active_defconfig
	cd corefs-builder
	make active_defconfig
	make -s
	cp output/images/* ../output/
}

make_linux () {
	cd corefs-builder
	make active_defconfig
	make -s linux-build
	cp output/images/* ../output/
}

make_uboot () {
	echo "booted"
}

make_clean () {
	cd corefs-builder
	make clean
}

make_edit () {
	cd corefs-builder
	make active_defconfig
	make menuconfig
}

build_help () {
	echo 'Use: build board-target buildtype [profile]'
	echo ' board-targets (required):'
	ls boards/*/board.conf | cut -d '/' -f 2 | sed 's/^/   /g'
	echo ' buildtype (optional):'
	echo '  edit, all, corefs, linux, uboot, clean'
	echo ' profiles (optional):'
	ls profiles/corefs/*/iotfapOS-core.conf | cut -d '/' -f 3 | sed 's/^/   /g'
}

# Check Target Exists
if [ "$TARGET" == "clean" ]; then
	make_clean
else
	if [ -f boards/"$TARGET"/board.conf ]; then
		source boards/"$TARGET"/board.conf
		build_config
		build
	else
		build_help	
	fi
fi
