#!/bin/bash
NCPU="2"
NRAM="256"

if [[ -n "$1" ]]; then
    COREFS="$1"
else
    COREFS="corefs.img"
fi


if [[ -f sys.k ]]; then
    qemu-system-aarch64 -M virt -cpu cortex-a57 -smp $NCPU -m $NRAM -nographic -kernel sys.k  -drive file="$COREFS",if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 -append "root=/dev/vda console=ttyAMA0 quiet" -netdev user,id=eth0 -device virtio-net-device,netdev=eth0 -net user,hostfwd=tcp::9995-:995,hostfwd=tcp::9996-:996,hostfwd=tcp::9997-:997,hostfwd=tcp::9998-:998,hostfwd=tcp::9999-:999

else
    echo "Error: Kernel file missing (sys.k)"
fi
