#!/bin/bash

qemu-system-i386 -M pc -smp 2 -m 128 -kernel "$1" -drive file="$2",if=virtio,format=raw -append "root=/dev/vda console=tty1 quiet" -net user,hostfwd=tcp::9992-:92,hostfwd=tcp::9996-:96,hostfwd=tcp::9997-:97,hostfwd=tcp::9998-:98,hostfwd=tcp::9999-:99
