#!/bin/bash

qemu-system-aarch64 -M virt -cpu cortex-a57 -nographic -smp 2 -m 128 -kernel "$1" -drive file="$2",if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 -append "root=/dev/vda console=ttyAMA0 quiet" -netdev user,id=eth0 -device virtio-net-device,netdev=eth0 -net user,hostfwd=tcp::9992-:92,hostfwd=tcp::9996-:96,hostfwd=tcp::9997-:97,hostfwd=tcp::9998-:98,hostfwd=tcp::9999-:99
