#!/bin/bash
qemu-system-arm -M vexpress-a9 -smp 2 -m 256 -nographic -kernel sys.k -dtb sys.dtb  -drive file=corefs.img,if=sd,format=raw -append "console=ttyAMA0,115200 root=/dev/mmcblk0 quiet" -net nic,model=lan9118  -net user,hostfwd=tcp::9992-:22

